/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_josuezelaya;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_principal = new javax.swing.JTabbedPane();
        panel_operaciones = new javax.swing.JPanel();
        pane_operaciones = new javax.swing.JTabbedPane();
        panel_agregar = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        tab_pane_tipo = new javax.swing.JTabbedPane();
        panel_empleado = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_empleo = new javax.swing.JTextField();
        panel_estudiante = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_carrera = new javax.swing.JTextField();
        panel_politico = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cb_partidos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_edad = new javax.swing.JTextField();
        tf_id = new javax.swing.JTextField();
        cb_departamento = new javax.swing.JComboBox<>();
        tf_boleto_loto = new javax.swing.JTextField();
        tf_dinero = new javax.swing.JTextField();
        boton_guardar = new javax.swing.JToggleButton();
        panel_modificar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cb_persona2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_fila = new javax.swing.JTextField();
        tf_columna = new javax.swing.JTextField();
        tf_nuevo = new javax.swing.JTextField();
        modificar_boton = new javax.swing.JToggleButton();
        panel_eliminar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cb_persona1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        eliminar_boton = new javax.swing.JToggleButton();
        panel_reporte = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cb_persona = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        panel2 = new javax.swing.JPanel();
        panel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab_principal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab_principalStateChanged(evt);
            }
        });

        pane_operaciones.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pane_operacionesStateChanged(evt);
            }
        });

        jToggleButton1.setText("GUARDAR");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jLabel7.setText("Empleo");

        javax.swing.GroupLayout panel_empleadoLayout = new javax.swing.GroupLayout(panel_empleado);
        panel_empleado.setLayout(panel_empleadoLayout);
        panel_empleadoLayout.setHorizontalGroup(
            panel_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_empleadoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panel_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_empleo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        panel_empleadoLayout.setVerticalGroup(
            panel_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_empleadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(tf_empleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        tab_pane_tipo.addTab("Empleado", panel_empleado);

        jLabel8.setText("Carrera Estudiantil");

        javax.swing.GroupLayout panel_estudianteLayout = new javax.swing.GroupLayout(panel_estudiante);
        panel_estudiante.setLayout(panel_estudianteLayout);
        panel_estudianteLayout.setHorizontalGroup(
            panel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_estudianteLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(panel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        panel_estudianteLayout.setVerticalGroup(
            panel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_estudianteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(tf_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        tab_pane_tipo.addTab("Estudiante", panel_estudiante);

        jLabel9.setText("Partidos Politicos");

        cb_partidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Liberal", "Libre", "PAC", "Alianza", " ", " " }));

        javax.swing.GroupLayout panel_politicoLayout = new javax.swing.GroupLayout(panel_politico);
        panel_politico.setLayout(panel_politicoLayout);
        panel_politicoLayout.setHorizontalGroup(
            panel_politicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_politicoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(92, 92, 92)
                .addComponent(cb_partidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_politicoLayout.setVerticalGroup(
            panel_politicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_politicoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panel_politicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_partidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_pane_tipo.addTab("Politico", panel_politico);

        jLabel1.setText("Nombre Completo");

        jLabel2.setText("Edad");

        jLabel3.setText("ID");

        jLabel4.setText("ID Boleto de Loto");

        jLabel5.setText("Departamento");

        jLabel6.setText("Dinero en su Bolsillo");

        tf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreActionPerformed(evt);
            }
        });

        cb_departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atlantida", "Colón", "Comayagua", "Copán ", "Cortés", "Choluteca", "El Paraíso", "Francisco Morazan", "Gracias a Dios", "Intibucá", "Islas de la Bahía ", "La Paz ", "Lempira", "Ocotepeque", "Olancho", "Santa Bárbara", "Valle", " Yoro " }));

        boton_guardar.setText("Guardar");
        boton_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_guardarMouseClicked(evt);
            }
        });
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_agregarLayout = new javax.swing.GroupLayout(panel_agregar);
        panel_agregar.setLayout(panel_agregarLayout);
        panel_agregarLayout.setHorizontalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_agregarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton1)
                        .addGap(307, 307, 307))
                    .addGroup(panel_agregarLayout.createSequentialGroup()
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_agregarLayout.createSequentialGroup()
                                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_agregarLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_boleto_loto, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panel_agregarLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tab_pane_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109))))
        );
        panel_agregarLayout.setVerticalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_agregarLayout.createSequentialGroup()
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_boleto_loto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tab_pane_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_agregarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_dinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_agregarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(boton_guardar)))
                .addGap(152, 152, 152)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_operaciones.addTab("Agregar", panel_agregar);

        jLabel12.setText("Personas");

        cb_persona2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_persona2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_persona2ItemStateChanged(evt);
            }
        });
        cb_persona2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_persona2ActionPerformed(evt);
            }
        });

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Id", "Departamento", "Dinero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla3);

        jLabel13.setText("Fila");

        jLabel14.setText("Columna");

        jLabel15.setText("Nuevo Valor");

        modificar_boton.setText("Modificar");
        modificar_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificar_botonMouseClicked(evt);
            }
        });
        modificar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_modificarLayout = new javax.swing.GroupLayout(panel_modificar);
        panel_modificar.setLayout(panel_modificarLayout);
        panel_modificarLayout.setHorizontalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_modificarLayout.createSequentialGroup()
                .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_modificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31)
                        .addComponent(cb_persona2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_modificarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_modificarLayout.createSequentialGroup()
                                .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_columna, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(tf_fila)))
                            .addGroup(panel_modificarLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                        .addGap(100, 100, 100))
                    .addGroup(panel_modificarLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(modificar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_modificarLayout.setVerticalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarLayout.createSequentialGroup()
                .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_modificarLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cb_persona2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_modificarLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tf_fila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_columna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tf_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addComponent(modificar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pane_operaciones.addTab("Modificar", panel_modificar);

        jLabel11.setText("Personas");

        cb_persona1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_persona1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_persona1ItemStateChanged(evt);
            }
        });
        cb_persona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_persona1ActionPerformed(evt);
            }
        });

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "ID", "Departamento", "Dinero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla2);

        eliminar_boton.setText("Eliminar");
        eliminar_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar_botonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_eliminarLayout = new javax.swing.GroupLayout(panel_eliminar);
        panel_eliminar.setLayout(panel_eliminarLayout);
        panel_eliminarLayout.setHorizontalGroup(
            panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_eliminarLayout.createSequentialGroup()
                .addGroup(panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_eliminarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_eliminarLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(26, 26, 26)
                                .addComponent(cb_persona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_eliminarLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(eliminar_boton)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        panel_eliminarLayout.setVerticalGroup(
            panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_eliminarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_persona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(eliminar_boton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pane_operaciones.addTab("Eliminar", panel_eliminar);

        jLabel10.setText("Personas");

        cb_persona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_persona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_personaItemStateChanged(evt);
            }
        });
        cb_persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_personaActionPerformed(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "ID Boleto", "Departamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla1);

        javax.swing.GroupLayout panel_reporteLayout = new javax.swing.GroupLayout(panel_reporte);
        panel_reporte.setLayout(panel_reporteLayout);
        panel_reporteLayout.setHorizontalGroup(
            panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reporteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_reporteLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(51, 51, 51)
                        .addComponent(cb_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        panel_reporteLayout.setVerticalGroup(
            panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reporteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pane_operaciones.addTab("Reporte", panel_reporte);

        javax.swing.GroupLayout panel_operacionesLayout = new javax.swing.GroupLayout(panel_operaciones);
        panel_operaciones.setLayout(panel_operacionesLayout);
        panel_operacionesLayout.setHorizontalGroup(
            panel_operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_operacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane_operaciones)
                .addContainerGap())
        );
        panel_operacionesLayout.setVerticalGroup(
            panel_operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_operacionesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pane_operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tab_principal.addTab("Operaciones Admistrativas", panel_operaciones);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        tab_principal.addTab("tab2", panel2);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        tab_principal.addTab("tab3", panel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tab_principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tab_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_principalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab_principalStateChanged
        // TODO add your handling code here:
        if (tab_principal.getSelectedIndex()==0){
            System.out.println("Entro 1");
            String contrasena2 =JOptionPane.showInputDialog(null, "Ingrese su contraseña");
            if (contrasena2.equals(contrasena)){
                System.out.println("Excelente");
                JOptionPane.showMessageDialog(null, "Bienvenido Ingeniero");
                pane_operaciones.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "La contraseña es incorrecta no es el Ingeniero");
                pane_operaciones.setVisible(false);
            }
        }

    }//GEN-LAST:event_tab_principalStateChanged

    private void tf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void boton_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_guardarMouseClicked
        // TODO add your handling code here:
        try {
            String nombre = tf_nombre.getText();
            int edad = Integer.parseInt(tf_edad.getText());
            long id = Long.parseLong(tf_id.getText());
            long id_loto = Long.parseLong(tf_boleto_loto.getText());
            String departamento = cb_departamento.getSelectedItem().toString();
            int dinero = Integer.parseInt(tf_dinero.getText());
            if (tab_pane_tipo.getSelectedIndex() == 0) {//empleado
                String empleo = tf_empleo.getText();
                lista.add(new Empleado(empleo, nombre, edad, id, id_loto, departamento, dinero));
            } else if (tab_pane_tipo.getSelectedIndex() == 1) {//estudiante
                String carrera=tf_carrera.getText();
                lista.add(new Estudiante(carrera, nombre, edad, id, id_loto, departamento, dinero));
            } else if (tab_pane_tipo.getSelectedIndex()==2){// politico
               String partido=cb_partidos.getSelectedItem().toString();
               lista.add(new Politico(partido, nombre, edad, id, id_loto, departamento, dinero));
            }
            JOptionPane.showMessageDialog(this, "Fue agregado exitosamente");
           
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
         //resetear todo
            tf_nombre.setText("");
            tf_edad.setText("");
            tf_id.setText("");
            tf_boleto_loto.setText("");
            cb_departamento.setSelectedIndex(0);
            tf_dinero.setText("");
            tf_empleo.setText("");
            tf_carrera.setText("");
            cb_partidos.setSelectedIndex(0);
    }//GEN-LAST:event_boton_guardarMouseClicked

    private void pane_operacionesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pane_operacionesStateChanged
        // TODO add your handling code here:
        if (pane_operaciones.getSelectedIndex()==3){
             DefaultComboBoxModel modelo=
                    new DefaultComboBoxModel();
            for (Persona temp : lista) {
                modelo.addElement(temp);
            }
            cb_persona.setModel(modelo);
        }
        if (pane_operaciones.getSelectedIndex()==2){
            DefaultComboBoxModel modelo=
                    new DefaultComboBoxModel();
            for (Persona te : lista) {
                modelo.addElement(te);
            }
            cb_persona1.setModel(modelo);
        }
        if (pane_operaciones.getSelectedIndex()==1){
            DefaultComboBoxModel modelo=
                    new DefaultComboBoxModel();
            for (Persona te : lista) {
                modelo.addElement(te);
            }
            cb_persona2.setModel(modelo);
        }
    }//GEN-LAST:event_pane_operacionesStateChanged

    private void cb_personaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_personaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange()==2){//van a ver 2 eventos
            Persona s=
                    (Persona) cb_persona.getSelectedItem();
            
                    Object [] newrow = {
                        s.getNombre(),
                        s.getEdad(),
                        s.getId_boleteria(),
                        s.getDepartamento()
                       
                    };
                    DefaultTableModel modelo=
                            (DefaultTableModel) tabla1.getModel();
                    modelo.addRow(newrow);
                    tabla1.setModel(modelo);
        }//fin del if
       
    }//GEN-LAST:event_cb_personaItemStateChanged

    private void cb_personaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_personaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_personaActionPerformed

    private void cb_persona1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_persona1ItemStateChanged
        // TODO add your handling code here:
         if (evt.getStateChange()==2){//van a ver 2 eventos
            Persona s=
                    (Persona) cb_persona1.getSelectedItem();
            
                    Object [] newrow = {
                        s.getNombre(),
                        s.getId(),
                        s.getDepartamento(),
                        s.getDinero()
                       
                    };
                    DefaultTableModel modelo=
                            (DefaultTableModel) tabla2.getModel();
                    modelo.addRow(newrow);
                    tabla2.setModel(modelo);
        }//fin del if
        
        
    }//GEN-LAST:event_cb_persona1ItemStateChanged

    private void cb_persona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_persona1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_persona1ActionPerformed

    private void eliminar_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_botonMouseClicked
        // TODO add your handling code here:
         if (tabla2.getSelectedRow()>=0){
            DefaultTableModel modelo=
                    (DefaultTableModel) tabla2.getModel();
            modelo.removeRow(tabla2.getSelectedRow());
            tabla2.setModel(modelo);
         }
    }//GEN-LAST:event_eliminar_botonMouseClicked

    private void cb_persona2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_persona2ItemStateChanged
        // TODO add your handling code here:
        
         if (evt.getStateChange()==2){//van a ver 2 eventos
            Persona s=
                    (Persona) cb_persona2.getSelectedItem();
            
                    Object [] newrow = {
                        s.getNombre(),
                        s.getId(),
                        s.getDepartamento(),
                        s.getDinero()
                       
                    };
                    DefaultTableModel modelo=
                            (DefaultTableModel) tabla3.getModel();
                    modelo.addRow(newrow);
                    tabla3.setModel(modelo);
        }//fin del if
    }//GEN-LAST:event_cb_persona2ItemStateChanged

    private void cb_persona2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_persona2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_persona2ActionPerformed

    private void modificar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_botonActionPerformed

    private void modificar_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_botonMouseClicked
        // TODO add your handling code here:
        int fila=Integer.parseInt(tf_fila.getText());
        int columna=Integer.parseInt(tf_columna.getText());
        tabla3.setValueAt(tf_nuevo.getText(), fila, columna);
    }//GEN-LAST:event_modificar_botonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        contrasena = JOptionPane.showInputDialog(null, "Ingrese su nueva contraseña");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boton_guardar;
    private javax.swing.JComboBox<String> cb_departamento;
    private javax.swing.JComboBox<String> cb_partidos;
    private javax.swing.JComboBox<String> cb_persona;
    private javax.swing.JComboBox<String> cb_persona1;
    private javax.swing.JComboBox<String> cb_persona2;
    private javax.swing.JToggleButton eliminar_boton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton modificar_boton;
    private javax.swing.JTabbedPane pane_operaciones;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel_agregar;
    private javax.swing.JPanel panel_eliminar;
    private javax.swing.JPanel panel_empleado;
    private javax.swing.JPanel panel_estudiante;
    private javax.swing.JPanel panel_modificar;
    private javax.swing.JPanel panel_operaciones;
    private javax.swing.JPanel panel_politico;
    private javax.swing.JPanel panel_reporte;
    private javax.swing.JTabbedPane tab_pane_tipo;
    private javax.swing.JTabbedPane tab_principal;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    private javax.swing.JTable tabla3;
    private javax.swing.JTextField tf_boleto_loto;
    private javax.swing.JTextField tf_carrera;
    private javax.swing.JTextField tf_columna;
    private javax.swing.JTextField tf_dinero;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_empleo;
    private javax.swing.JTextField tf_fila;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nuevo;
    // End of variables declaration//GEN-END:variables
 static String contrasena;
    ArrayList<Persona> lista = new ArrayList();

}
